# Generated by scripts/generate.ts from data/document-types.json.
# DO NOT EDIT BY HAND — run `pnpm run generate` to regenerate.
from __future__ import annotations

from enum import Enum


class DocumentType(str, Enum):
    """Canonical Gaceta Oficial de Panamá document types."""

    LAW = "law"
    DECREE = "decree"
    RESOLUTION = "resolution"
    AGREEMENT = "agreement"
    RESUELTO = "resuelto"
    NOTICE = "notice"
    CIRCULAR = "circular"
    CONTRACT = "contract"
    ACTA = "acta"
    ADDENDUM = "addendum"
    CODE = "code"
    CONSTITUTION = "constitution"
    UNKNOWN = "unknown"


class DocumentSubtype(str, Enum):
    """Canonical Gaceta Oficial de Panamá document subtypes."""

    EXECUTIVE_DECREE = "executive_decree"
    DECREE_LAW = "decree_law"
    CABINET_DECREE = "cabinet_decree"
    MAYORAL_DECREE = "mayoral_decree"
    PERSONNEL_DECREE = "personnel_decree"
    OTHER_DECREE = "other_decree"
    CABINET_RESOLUTION = "cabinet_resolution"
    ADMINISTRATIVE_RESOLUTION = "administrative_resolution"
    MINISTERIAL_RESOLUTION = "ministerial_resolution"
    SUPERINTENDENCY_RESOLUTION = "superintendency_resolution"
    BOARD_RESOLUTION = "board_resolution"
    OTHER_RESOLUTION = "other_resolution"
    MUNICIPAL_AGREEMENT = "municipal_agreement"
    OTHER_AGREEMENT = "other_agreement"
