# Generated by scripts/generate.ts from the canonical data files.
# DO NOT EDIT BY HAND — run `pnpm run generate` to regenerate.
from __future__ import annotations

from enum import Enum


class DocumentType(str, Enum):
    """Canonical Gaceta Oficial de Panamá document types."""

    LAW = "law"
    DECREE = "decree"
    RESOLUTION = "resolution"
    AGREEMENT = "agreement"
    RESUELTO = "resuelto"
    NOTICE = "notice"
    CIRCULAR = "circular"
    CONTRACT = "contract"
    ACTA = "acta"
    ADDENDUM = "addendum"
    CODE = "code"
    CONSTITUTION = "constitution"
    UNKNOWN = "unknown"


class DocumentSubtype(str, Enum):
    """Canonical Gaceta Oficial de Panamá document subtypes."""

    EXECUTIVE_DECREE = "executive_decree"
    DECREE_LAW = "decree_law"
    CABINET_DECREE = "cabinet_decree"
    MAYORAL_DECREE = "mayoral_decree"
    PERSONNEL_DECREE = "personnel_decree"
    OTHER_DECREE = "other_decree"
    CABINET_RESOLUTION = "cabinet_resolution"
    ADMINISTRATIVE_RESOLUTION = "administrative_resolution"
    MINISTERIAL_RESOLUTION = "ministerial_resolution"
    SUPERINTENDENCY_RESOLUTION = "superintendency_resolution"
    BOARD_RESOLUTION = "board_resolution"
    OTHER_RESOLUTION = "other_resolution"
    MUNICIPAL_AGREEMENT = "municipal_agreement"
    OTHER_AGREEMENT = "other_agreement"


class LegalSubject(str, Enum):
    """Canonical LexLatam legal subjects."""

    ADMINISTRATIVE = "administrative"
    BANKING_FINANCE = "banking_finance"
    CIVIL = "civil"
    CIVIL_PROCEDURE = "civil_procedure"
    COMMERCIAL = "commercial"
    CONSTITUTIONAL = "constitutional"
    CONSUMER = "consumer"
    CORPORATE = "corporate"
    CRIMINAL = "criminal"
    CRIMINAL_PROCEDURE = "criminal_procedure"
    EMPLOYMENT = "employment"
    ENVIRONMENTAL = "environmental"
    FAMILY = "family"
    IMMIGRATION = "immigration"
    MARITIME = "maritime"
    PROPERTY_REAL_ESTATE = "property_real_estate"
    PUBLIC_PROCUREMENT = "public_procurement"
    SOCIAL_SECURITY = "social_security"
    TAX = "tax"
    OTHER = "other"
    UNKNOWN = "unknown"
