// Generated by scripts/generate.ts from data/document-types.json.
// DO NOT EDIT BY HAND — run `pnpm run generate` to regenerate.

export type DocumentType =
  | "law"
  | "decree"
  | "resolution"
  | "agreement"
  | "resuelto"
  | "notice"
  | "circular"
  | "contract"
  | "acta"
  | "addendum"
  | "code"
  | "constitution"
  | "unknown";

export type DocumentSubtype =
  | "executive_decree"
  | "decree_law"
  | "cabinet_decree"
  | "mayoral_decree"
  | "personnel_decree"
  | "other_decree"
  | "cabinet_resolution"
  | "administrative_resolution"
  | "ministerial_resolution"
  | "superintendency_resolution"
  | "board_resolution"
  | "other_resolution"
  | "municipal_agreement"
  | "other_agreement";

export interface Labels {
  label_es: string;
  label_en: string;
}

export const TYPE_LABELS: Record<DocumentType, Labels> = {
  "law": { label_es: "Ley", label_en: "Law" },
  "decree": { label_es: "Decreto", label_en: "Decree" },
  "resolution": { label_es: "Resolución", label_en: "Resolution" },
  "agreement": { label_es: "Acuerdo", label_en: "Agreement" },
  "resuelto": { label_es: "Resuelto", label_en: "Resuelto" },
  "notice": { label_es: "Aviso", label_en: "Notice" },
  "circular": { label_es: "Circular", label_en: "Circular" },
  "contract": { label_es: "Contrato", label_en: "Contract" },
  "acta": { label_es: "Acta", label_en: "Minutes" },
  "addendum": { label_es: "Adenda", label_en: "Addendum" },
  "code": { label_es: "Código", label_en: "Code" },
  "constitution": { label_es: "Constitución", label_en: "Constitution" },
  "unknown": { label_es: "Desconocido", label_en: "Unknown" },
};

export const SUBTYPE_LABELS: Record<DocumentSubtype, Labels> = {
  "executive_decree": { label_es: "Decreto Ejecutivo", label_en: "Executive Decree" },
  "decree_law": { label_es: "Decreto Ley", label_en: "Decree-Law" },
  "cabinet_decree": { label_es: "Decreto de Gabinete", label_en: "Cabinet Decree" },
  "mayoral_decree": { label_es: "Decreto Alcaldicio", label_en: "Mayoral Decree" },
  "personnel_decree": { label_es: "Decreto de Personal", label_en: "Personnel Decree" },
  "other_decree": { label_es: "Otro Decreto", label_en: "Other Decree" },
  "cabinet_resolution": { label_es: "Resolución de Gabinete", label_en: "Cabinet Resolution" },
  "administrative_resolution": { label_es: "Resolución Administrativa", label_en: "Administrative Resolution" },
  "ministerial_resolution": { label_es: "Resolución Ministerial", label_en: "Ministerial Resolution" },
  "superintendency_resolution": { label_es: "Resolución de Superintendencia", label_en: "Superintendency Resolution" },
  "board_resolution": { label_es: "Resolución de Junta Directiva", label_en: "Board Resolution" },
  "other_resolution": { label_es: "Otra Resolución", label_en: "Other Resolution" },
  "municipal_agreement": { label_es: "Acuerdo Municipal", label_en: "Municipal Agreement" },
  "other_agreement": { label_es: "Otro Acuerdo", label_en: "Other Agreement" },
};

export const SUBTYPE_PARENTS: Record<DocumentSubtype, DocumentType> = {
  "executive_decree": "decree",
  "decree_law": "decree",
  "cabinet_decree": "decree",
  "mayoral_decree": "decree",
  "personnel_decree": "decree",
  "other_decree": "decree",
  "cabinet_resolution": "resolution",
  "administrative_resolution": "resolution",
  "ministerial_resolution": "resolution",
  "superintendency_resolution": "resolution",
  "board_resolution": "resolution",
  "other_resolution": "resolution",
  "municipal_agreement": "agreement",
  "other_agreement": "agreement",
};
