/**
 * Code generator for the LexLatam taxonomy.
 *
 * Reads the canonical document-type and legal-subject data and emits the
 * typed bindings consumed by the Python and TypeScript packages:
 *
 *   python/lexlatam_taxonomy/types.py    GENERATED enums
 *   python/lexlatam_taxonomy/data.json   verbatim copy of the source
 *   python/lexlatam_taxonomy/legal-subjects.json
 *   typescript/src/types.ts              GENERATED union types + label tables
 *   typescript/src/data.json             verbatim copy of the source
 *   typescript/src/legal-subjects.json
 *
 * The emitted files are committed. CI runs this script and then
 * `git diff --exit-code`, so data/ and the bindings can never drift.
 */
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

interface Labels {
  label_es: string;
  label_en: string;
}
interface Taxonomy {
  version: string;
  types: Record<string, Labels>;
  subtypes: Record<string, Labels & { parent: string }>;
  mappings: Record<string, { type: string; subtype: string | null }>;
  fallbacks: { prefix: string; type: string; subtype: string | null }[];
}
interface LegalSubjectLabels {
  label_es: string;
  label_en?: string;
  includes: string;
  excludes: string;
}
interface LegalSubjects {
  version: string;
  subjects: Record<string, LegalSubjectLabels>;
  content_category_crosswalk: Record<string, string>;
}

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(ROOT, "data", "document-types.json");
const LEGAL_SUBJECT_SOURCE = join(ROOT, "data", "legal-subjects.json");

const data: Taxonomy = JSON.parse(readFileSync(SOURCE, "utf-8"));
const legalSubjects: LegalSubjects = JSON.parse(
  readFileSync(LEGAL_SUBJECT_SOURCE, "utf-8"),
);

const GENERATED_NOTICE =
  "Generated by scripts/generate.ts from the canonical data files.\n" +
  "DO NOT EDIT BY HAND — run `pnpm run generate` to regenerate.";

/** Convert a canonical identifier to a Python enum member name. */
function enumName(canonical: string): string {
  return canonical.toUpperCase();
}

function quote(value: string): string {
  return JSON.stringify(value);
}

// --- python/lexlatam_taxonomy/types.py -------------------------------------
function generatePython(): string {
  const lines: string[] = [];
  for (const line of GENERATED_NOTICE.split("\n")) lines.push(`# ${line}`);
  lines.push("from __future__ import annotations");
  lines.push("");
  lines.push("from enum import Enum");
  lines.push("");
  lines.push("");
  lines.push("class DocumentType(str, Enum):");
  lines.push('    """Canonical Gaceta Oficial de Panamá document types."""');
  lines.push("");
  for (const canonical of Object.keys(data.types)) {
    lines.push(`    ${enumName(canonical)} = ${quote(canonical)}`);
  }
  lines.push("");
  lines.push("");
  lines.push("class DocumentSubtype(str, Enum):");
  lines.push('    """Canonical Gaceta Oficial de Panamá document subtypes."""');
  lines.push("");
  for (const canonical of Object.keys(data.subtypes)) {
    lines.push(`    ${enumName(canonical)} = ${quote(canonical)}`);
  }
  lines.push("");
  lines.push("");
  lines.push("class LegalSubject(str, Enum):");
  lines.push('    """Canonical LexLatam legal subjects."""');
  lines.push("");
  for (const canonical of Object.keys(legalSubjects.subjects)) {
    lines.push(`    ${enumName(canonical)} = ${quote(canonical)}`);
  }
  lines.push("");
  return lines.join("\n");
}

// --- typescript/src/types.ts -----------------------------------------------
function generateTypeScript(): string {
  const lines: string[] = [];
  for (const line of GENERATED_NOTICE.split("\n")) lines.push(`// ${line}`);
  lines.push("");

  const typeKeys = Object.keys(data.types);
  const subtypeKeys = Object.keys(data.subtypes);
  const legalSubjectKeys = Object.keys(legalSubjects.subjects);

  lines.push("export type DocumentType =");
  typeKeys.forEach((k, i) => {
    lines.push(`  | ${quote(k)}${i === typeKeys.length - 1 ? ";" : ""}`);
  });
  lines.push("");
  lines.push("export type DocumentSubtype =");
  subtypeKeys.forEach((k, i) => {
    lines.push(`  | ${quote(k)}${i === subtypeKeys.length - 1 ? ";" : ""}`);
  });
  lines.push("");
  lines.push("export interface Labels {");
  lines.push("  label_es: string;");
  lines.push("  label_en: string;");
  lines.push("}");
  lines.push("");
  lines.push("export type LegalSubject =");
  legalSubjectKeys.forEach((k, i) => {
    lines.push(`  | ${quote(k)}${i === legalSubjectKeys.length - 1 ? ";" : ""}`);
  });
  lines.push("");
  lines.push("export const TYPE_LABELS: Record<DocumentType, Labels> = {");
  for (const [k, v] of Object.entries(data.types)) {
    lines.push(
      `  ${quote(k)}: { label_es: ${quote(v.label_es)}, label_en: ${quote(v.label_en)} },`,
    );
  }
  lines.push("};");
  lines.push("");

  lines.push(
    "export const LEGAL_SUBJECT_LABELS: Record<LegalSubject, string> = {",
  );
  for (const [k, v] of Object.entries(legalSubjects.subjects)) {
    lines.push(`  ${quote(k)}: ${quote(v.label_es)},`);
  }
  lines.push("};");
  lines.push("");

  lines.push(
    "export const CONTENT_CATEGORY_TO_LEGAL_SUBJECT = {",
  );
  for (const [source, target] of Object.entries(
    legalSubjects.content_category_crosswalk,
  )) {
    lines.push(`  ${quote(source)}: ${quote(target)},`);
  }
  lines.push("} as const satisfies Record<string, LegalSubject>;");
  lines.push("");

  lines.push("export const SUBTYPE_LABELS: Record<DocumentSubtype, Labels> = {");
  for (const [k, v] of Object.entries(data.subtypes)) {
    lines.push(
      `  ${quote(k)}: { label_es: ${quote(v.label_es)}, label_en: ${quote(v.label_en)} },`,
    );
  }
  lines.push("};");
  lines.push("");

  lines.push(
    "export const SUBTYPE_PARENTS: Record<DocumentSubtype, DocumentType> = {",
  );
  for (const [k, v] of Object.entries(data.subtypes)) {
    lines.push(`  ${quote(k)}: ${quote(v.parent)},`);
  }
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

writeFileSync(join(ROOT, "python/lexlatam_taxonomy/types.py"), generatePython());
writeFileSync(join(ROOT, "typescript/src/types.ts"), generateTypeScript());

// data.json is copied verbatim so both packages embed the exact source bytes.
copyFileSync(SOURCE, join(ROOT, "python/lexlatam_taxonomy/data.json"));
copyFileSync(SOURCE, join(ROOT, "typescript/src/data.json"));
copyFileSync(
  LEGAL_SUBJECT_SOURCE,
  join(ROOT, "python/lexlatam_taxonomy/legal-subjects.json"),
);
copyFileSync(
  LEGAL_SUBJECT_SOURCE,
  join(ROOT, "typescript/src/legal-subjects.json"),
);

console.log("Generated:");
console.log("  python/lexlatam_taxonomy/types.py");
console.log("  python/lexlatam_taxonomy/data.json");
console.log("  typescript/src/types.ts");
console.log("  typescript/src/data.json");
console.log("  python/lexlatam_taxonomy/legal-subjects.json");
console.log("  typescript/src/legal-subjects.json");
