/**
 * Code generator for the LexLatam taxonomy.
 *
 * Reads data/document-types.json (the single source of truth) and emits the
 * typed bindings consumed by the Python and TypeScript packages:
 *
 *   python/lexlatam_taxonomy/types.py    GENERATED enums
 *   python/lexlatam_taxonomy/data.json   verbatim copy of the source
 *   typescript/src/types.ts              GENERATED union types + label tables
 *   typescript/src/data.json             verbatim copy of the source
 *
 * The emitted files are committed. CI runs this script and then
 * `git diff --exit-code`, so data/ and the bindings can never drift.
 */
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

interface Labels {
  label_es: string;
  label_en: string;
}
interface Taxonomy {
  version: string;
  types: Record<string, Labels>;
  subtypes: Record<string, Labels & { parent: string }>;
  mappings: Record<string, { type: string; subtype: string | null }>;
  fallbacks: { prefix: string; type: string; subtype: string | null }[];
}

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(ROOT, "data", "document-types.json");

const data: Taxonomy = JSON.parse(readFileSync(SOURCE, "utf-8"));

const GENERATED_NOTICE =
  "Generated by scripts/generate.ts from data/document-types.json.\n" +
  "DO NOT EDIT BY HAND — run `pnpm run generate` to regenerate.";

/** Convert a canonical identifier to a Python enum member name. */
function enumName(canonical: string): string {
  return canonical.toUpperCase();
}

function quote(value: string): string {
  return JSON.stringify(value);
}

// --- python/lexlatam_taxonomy/types.py -------------------------------------
function generatePython(): string {
  const lines: string[] = [];
  for (const line of GENERATED_NOTICE.split("\n")) lines.push(`# ${line}`);
  lines.push("from __future__ import annotations");
  lines.push("");
  lines.push("from enum import Enum");
  lines.push("");
  lines.push("");
  lines.push("class DocumentType(str, Enum):");
  lines.push('    """Canonical Gaceta Oficial de Panamá document types."""');
  lines.push("");
  for (const canonical of Object.keys(data.types)) {
    lines.push(`    ${enumName(canonical)} = ${quote(canonical)}`);
  }
  lines.push("");
  lines.push("");
  lines.push("class DocumentSubtype(str, Enum):");
  lines.push('    """Canonical Gaceta Oficial de Panamá document subtypes."""');
  lines.push("");
  for (const canonical of Object.keys(data.subtypes)) {
    lines.push(`    ${enumName(canonical)} = ${quote(canonical)}`);
  }
  lines.push("");
  return lines.join("\n");
}

// --- typescript/src/types.ts -----------------------------------------------
function generateTypeScript(): string {
  const lines: string[] = [];
  for (const line of GENERATED_NOTICE.split("\n")) lines.push(`// ${line}`);
  lines.push("");

  const typeKeys = Object.keys(data.types);
  const subtypeKeys = Object.keys(data.subtypes);

  lines.push("export type DocumentType =");
  typeKeys.forEach((k, i) => {
    lines.push(`  | ${quote(k)}${i === typeKeys.length - 1 ? ";" : ""}`);
  });
  lines.push("");
  lines.push("export type DocumentSubtype =");
  subtypeKeys.forEach((k, i) => {
    lines.push(`  | ${quote(k)}${i === subtypeKeys.length - 1 ? ";" : ""}`);
  });
  lines.push("");
  lines.push("export interface Labels {");
  lines.push("  label_es: string;");
  lines.push("  label_en: string;");
  lines.push("}");
  lines.push("");

  lines.push("export const TYPE_LABELS: Record<DocumentType, Labels> = {");
  for (const [k, v] of Object.entries(data.types)) {
    lines.push(
      `  ${quote(k)}: { label_es: ${quote(v.label_es)}, label_en: ${quote(v.label_en)} },`,
    );
  }
  lines.push("};");
  lines.push("");

  lines.push("export const SUBTYPE_LABELS: Record<DocumentSubtype, Labels> = {");
  for (const [k, v] of Object.entries(data.subtypes)) {
    lines.push(
      `  ${quote(k)}: { label_es: ${quote(v.label_es)}, label_en: ${quote(v.label_en)} },`,
    );
  }
  lines.push("};");
  lines.push("");

  lines.push(
    "export const SUBTYPE_PARENTS: Record<DocumentSubtype, DocumentType> = {",
  );
  for (const [k, v] of Object.entries(data.subtypes)) {
    lines.push(`  ${quote(k)}: ${quote(v.parent)},`);
  }
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

writeFileSync(join(ROOT, "python/lexlatam_taxonomy/types.py"), generatePython());
writeFileSync(join(ROOT, "typescript/src/types.ts"), generateTypeScript());

// data.json is copied verbatim so both packages embed the exact source bytes.
copyFileSync(SOURCE, join(ROOT, "python/lexlatam_taxonomy/data.json"));
copyFileSync(SOURCE, join(ROOT, "typescript/src/data.json"));

console.log("Generated:");
console.log("  python/lexlatam_taxonomy/types.py");
console.log("  python/lexlatam_taxonomy/data.json");
console.log("  typescript/src/types.ts");
console.log("  typescript/src/data.json");
